### ISSUE TITLE
Harmless exception continuously being printed at console

### ISSUE THREAD

**Issue by anbhole** [allcount/allcountjs#110]
I am getting this exception at the console. The application otherwise is running fine.

`SyntaxError: Unexpected token u
    at Object.parse (native)
    at actionList (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/routes/actions-route.js:5:97)
    at Layer.handle [as handle_request] (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/route.js:131:13)
    at checkOnlyAuthenticated (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/services/config/routes-setup.js:39:21)
    at Layer.handle [as handle_request] (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/index.js:277:22
    at param (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/index.js:271:10)
    at route.checkReadPermissionMiddleware (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/routes/crud.js:15:13)
    at Layer.handle [as handle_request] (/Users/abhijit/Documents/SearchX/PinBiFlo/node_modules/allcountjs/node_modules/express/lib/router/layer.js:95:5)`

I am running this on OSX 10.11.4 and node v0.12.7. allcount is the only package installed.

**Comment by anbhole** [comment]
i have fixed this issue. will raise pull request. **because of this actions are not being listed.**
