### ISSUE TITLE
Internal server error while trying to delete entity

### ISSUE THREAD

**Issue by paveltiunov** [allcount/allcountjs#25]
```
TypeError: Cannot read property 'id' of null
    at /home/allcountjs/app/allcountjs/node_modules/allcountjs/services/referential-integrity.js:15:84
    at /home/allcountjs/app/allcountjs/node_modules/allcountjs/services/storage-driver.js:352:28
    at Object.exports.inScope (/home/allcountjs/app/allcountjs/node_modules/allcountjs/services/injection.js:136:18)
    at /home/allcountjs/app/allcountjs/node_modules/allcountjs/services/storage-driver.js:351:34
    at /home/allcountjs/app/allcountjs/node_modules/allcountjs/services/injection.js:209:86
    at Object.exports.restoreScope (/home/allcountjs/app/allcountjs/node_modules/allcountjs/services/injection.js:104:18)
    at /home/allcountjs/app/allcountjs/node_modules/allcountjs/services/injection.js:209:36
    at _fulfilled (/home/allcountjs/app/allcountjs/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/allcountjs/app/allcountjs/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/allcountjs/app/allcountjs/node_modules/q/q.js:749:13)
    at /home/allcountjs/app/allcountjs/node_modules/q/q.js:509:49
    at flush (/home/allcountjs/app/allcountjs/node_modules/q/q.js:108:17)
    at wrapped (/home/allcountjs/app/allcountjs/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrapped (/home/allcountjs/app/allcountjs/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at process._tickDomainCallback (node.js:492:13)
    at process.wrappedFunction (/home/allcountjs/app/allcountjs/node_modules/newrelic/lib/transaction/tracer/index.js:271:51)
```

**Comment by paveltiunov** [comment]
Reproduced when allcountjs server is accessed with proxy (particularly node-http-proxy).
